services:
  my_app:
    build:
      context: .
      dockerfile: src/app/Dockerfile
      target: development
    command: npm run start:dev my_app
    env_file:
      - src/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default
    depends_on:
      - database
      - redis
    ports:
      - '80:3000'

  redis:
    image: redis
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - .env
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis/data:/data